version: "3"

services:

  nginx:
    image: jc21/nginx-proxy-manager:latest
    
    container_name: npm
    hostname: npm

    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
    
    ports:
      - 80:80
      - 443:443
      - 9030:81

    environment:
      DB_MYSQL_HOST: "maria-db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: $PASSWORD
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: 'true'
      
    volumes:
      - npm:/data # 1
      - letsencrypt:/etc/letsencrypt #2
      
    depends_on:
      - maria-db
      
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      
    restart: unless-stopped

  maria-db:

    image: jc21/mariadb-aria:latest

    container_name: maria-db
    hostname: maria-db

    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: $PASSWORD

    volumes:
      - maria-db:/var/lib/mysql # 3

    labels:
      - "com.centurylinklabs.watchtower.enable=true"

    restart: unless-stopped


volumes:

  # 1
  npm:
    external:
      name: npm
  # 2    
  letsencrypt:
    external:
      name: letsencrypt
  # 3    
  maria-db:
    external:
      name: maria-db